language: node_js
node_js:
- 6.11.0
- 8.1.1
script:
- npm test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: allo.vince@gmail.com
  api_key:
    secure: Ppq1i+jU9LZAvXEX3rM0xeO/BEtBzg95U0+hOiLQ5lhWTvsTy190uU15I8SIhELgV1kP89mcYMkHPqkZUtQ4Nn7qpsWoFURUfh++YZNSH1bDfCIgfb+VXTJRPinLFewctIK7mOebShUm0czwrq+1kfmoFFolPZFXq/292SoEFRD22lNNphNUqLF4Ml78IB6PmeSURBtshZBkiwE6+EDtKWot/E7oCaNnvzgEFjypIEGMRO+bRtTEpXiSWsPIe45saIfYRI+YjR6TpKMqV03HzXmo1IiLQi78ZWIDBXXKG/6A7t7Hj2uTPefNd2WcxmtI6z7CYOXZKdZZJ5t+AaV5AdfOGdycpSDaj/+97EAujcBag09ML/z+ipXEg4pf9oKXhWeytCPbKfx1zaJATHOFVla0EeyGZeWdwoofbyUnBSx/ewfxruHMf76v/OQEfNbq6JnPL4U48LK24HgYmYJrInJe0yAkvsDHmJRRLNTAjUOfs6nm2AnybA4O7cuFkYhlkabxxqFEPXWMyrWHEdLBvSB31SsQao2A+94NZLVCaHtJgaylJV2Drlbrf4feLk/b6K0uXW+1DuKD3SuNwmnEwkDZSf9ZM5xjhFWmxEIwapfeZG8L+YRPPAaHF9nBIviTSZT9BGuCFU5XxSTldGGnzcK9fn4Pzpwscyz3d6+J6AE=
  on:
    tags: true
