language: node_js
node_js:
- 6.11.0
- 8.1.1
script:
- npm test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: allo.vince@gmail.com
  api_key:
    secure: OmirvH0hX+F3NAGhq9CO9J/2vDDTX6BBqD0KHyGh5mWBNcd7qZRL/zdBJYdE88K5rt9w0bAMx4Cf2LGDfj0sda/ZJqte8xi6tmWbwK7QBO5/SN0Mz3+0/7/ZlDhia+uJNAw7G9rYPWjalAmF3lMu+MNQLdI1HOSixDSAjrETED0387uRoPjZAcFLHMkrHK55xWrJInSkA1KZN3pLii7M6cxMxX++g23idDQ5FkRhjrj1lrKJPRDMF5VI20Qfr1bGllRU59k/jsOVBaouqkAhncErnfOjQYqHmRjCBoG0kSLFLmxNiKlzkFi6E3VyB9f4LKA5EPhYZE+AGmXDpY+1YpgEWUgddnof5bheYH3ns3TOX/4wHecHEYpDfjnIPq92y6op5yA2j8hCb7BR4bqK0puHYfzpwHLhK5vPhibzSSkRE6KDODJv7hlw0/9gOQnr3oD/Ir2FTP2OcDMCHDXf8KkS5MJJX+MqMH4CkqWr6Z9RmHn25GLiF7J6sgfodAjqb3lkQyu0SAmJsTmIBWeNy7HPrmNK45k2huguIaYnthXy4pu/eWxsmu0Z7n0PiRJfbvmZBkfsZZZNdHC4aUJGFwpKxA5o8O798Dy9ptjAdWonOtlK5bbyMv727il4qfT+d+5xg+FxKmYKybrZEQwyBb6D5qaN/QL6x5I9FGlrMT8=
  on:
    tags: true
