language: node_js
node_js:
- 6.10.3
- 8.0.0
script:
- npm run ava
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: xuqian@bmqb.com
  api_key:
    secure: wNjDb/Nho6vtq1pfKkMmJokbxdiC+Ul1Y4iGAeaUbrDF/E7Cd/lLcOo4xioZcftpb4aFaCJKgR5IZ1T6zY9eSJuq5Saz0j2hKrF2EzBWtemiKWt5QyWiGSLkvn5VSRiqQ51Mrj/TkptODg4a5Xvo1XYk8TtSGqU/kF7ycylZyCiS5/b3icsJHgpaJOSvK3n3INU7E+6edmst0bKH6X5RVZqNY2r1qW7AQ+sO9GlwxlmMvMDZK6/tgFGHqhodqaf1Qm1GlyblnrMlt8SL/QoSMzrlJAZL6qfA3WpN3V3+Pfea7hSvIhCX7diXydvNyTAIRLpYYNbFfKyI+1/CVu9smISF5dVpfi9RbSIpqo947r9WXKXDaqE96/0LUGAkT1PB2h4dsJrrtMK9KoG8Q/6JJNWS447Vz05imhpXnbqGOUVJkVt4jXxsquVejms5ef8OPFErHh2f2V4Ottsh9QaEbm3fAfMt5/l6zgI6K4LSXkx6o0ieLmqz3L5BZZQws4vGzV1FfwNZpFynf2VEUrnySlZcKOuieHAzcuo1nbfH/6RKLuHDisESTfo46V98JZxJMZewOlk9wb4+I3G5zF4+tLMx3LUlNqnagRObXB68oLADhM+FVgT/6xdKOH9IXtQzDGGe6G9bBD+aXd0rJCkjulclvE7ePPMDPHG2c+hIHgw=
  on:
    tags: true
    repo: bmqb/zmxy
